# Generated by Django 4.2 on 2023-12-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='email_adress',
            field=models.EmailField(max_length=254),
        ),
    ]
